In [34]:
import pandas as pd
import numpy as np

# Nivel 1 - Punto 1

# 1) Importar archivo usando la fila 4 como encabezado (header=3)
df = pd.read_excel(
    r"C:\Users\ramir\OneDrive\Escritorio\Ramiro\Cursos IT Academy\Bootcamp-Analisis-de-datos\Sprint-10\sprint10.xlsx",
    header=3
)

# Verificamos
df

,Unnamed: 0,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional
0,0,Inês,Ferreira Silva,16928694K,Portugal,Lisboa,25,2,1953,D,1.144 €,NaN,1.0,Grup B
1,1,Clara,Sánchez Martínez,27724652S,Espanya,Barcelona,18,3,1996,D,1.253 €,1.0,NaN,Grup A
2,2,Fatima,Fassi,38141675A,Marroc,Rabat,6,11,2005,A,1.441 €,1.0,NaN,Grup A
3,3,Khadija,Bennani Bennani,59157262R,Marroc,Rabat,20,1,1995,D,1.944 €,NaN,1.0,Grup B
4,4,Toni,Sánchez García,69630528M,Espanya,Barcelona,9,8,1999,H,1.043 €,NaN,1.0,Grup A
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,995,Marta,Ferrer Ferrer,25161375F,Espanya,Sevilla,1,6,1951,D,1.216 €,NaN,1.0,Grup B
996,996,Joan,García,52145541P,Espanya,Sevilla,11,4,1959,H,971 €,NaN,1.0,Grup A
997,997,Laia,Ferrer Martínez,69760120X,Espanya,Barcelona,11,11,1980,D,682 €,NaN,1.0,Grup A
998,998,Jordi,García,82947791W,Espanya,Barcelona,23,5,1984,H,1.699 €,1.0,NaN,Grup C
999,999,Clara,Sánchez López,89253307W,Espanya,Bilbao,1,8,1952,D,1.217 €,NaN,1.0,Grup A

In [35]:
# 1.1) Eliminar la columna 'Unnamed', se visualiza duplicado, y no aporta nada al análisis
df = df.drop(columns=["Unnamed: 0"])

# Verificamos
df

,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional
0,Inês,Ferreira Silva,16928694K,Portugal,Lisboa,25,2,1953,D,1.144 €,NaN,1.0,Grup B
1,Clara,Sánchez Martínez,27724652S,Espanya,Barcelona,18,3,1996,D,1.253 €,1.0,NaN,Grup A
2,Fatima,Fassi,38141675A,Marroc,Rabat,6,11,2005,A,1.441 €,1.0,NaN,Grup A
3,Khadija,Bennani Bennani,59157262R,Marroc,Rabat,20,1,1995,D,1.944 €,NaN,1.0,Grup B
4,Toni,Sánchez García,69630528M,Espanya,Barcelona,9,8,1999,H,1.043 €,NaN,1.0,Grup A
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,Marta,Ferrer Ferrer,25161375F,Espanya,Sevilla,1,6,1951,D,1.216 €,NaN,1.0,Grup B
996,Joan,García,52145541P,Espanya,Sevilla,11,4,1959,H,971 €,NaN,1.0,Grup A
997,Laia,Ferrer Martínez,69760120X,Espanya,Barcelona,11,11,1980,D,682 €,NaN,1.0,Grup A
998,Jordi,García,82947791W,Espanya,Barcelona,23,5,1984,H,1.699 €,1.0,NaN,Grup C
999,Clara,Sánchez López,89253307W,Espanya,Bilbao,1,8,1952,D,1.217 €,NaN,1.0,Grup A

In [36]:
# 2) Ordenar por país y luego por ciudad
df_sorted = df.sort_values(by=["País d'origen", "Ciutat"], ascending=[True, True])

df_sorted = df_sorted.copy()

# Verificamos
df_sorted

,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional
21,Mia,Schneider Fischer,28973553Z,Alemanya,Berlín,22,10,1976,A,951 €,NaN,1.0,Grup A
154,Laura,Schneider Fischer,37399141L,Alemanya,Berlín,2,2,1958,D,1.769 €,1.0,NaN,Grup B
224,Lea,Schneider Schneider,37368317L,Alemanya,Berlín,23,10,2005,D,2.013 €,NaN,1.0,Grup B
278,Mia,Fischer,21390098Z,Alemanya,Berlín,11,8,1950,D,1.557 €,1.0,NaN,Grup B
602,Jonas,Schneider,44060014R,Alemanya,Berlín,22,11,1985,H,2.754 €,1.0,NaN,Grup D
...,...,...,...,...,...,...,...,...,...,...,...,...,...
547,Emily,Taylor Jones,89577876S,Regne Unit,Manchester,28,3,1958,D,2.033 €,NaN,1.0,Grup B
728,George,Brown Jones,57441590Y,Regne Unit,Manchester,27,12,1979,H,1.130 €,1.0,NaN,Grup A
751,Olivia,Brown Brown,58204038A,Regne Unit,Manchester,28,8,1952,A,1.023 €,NaN,1.0,Grup A
854,Isla,Jones Brown,28367234K,Regne Unit,Manchester,28,3,1999,D,1.197 €,NaN,1.0,Grup A
872,William,Smith,82046699J,Regne Unit,Manchester,19,5,1997,H,1.405 €,1.0,NaN,Grup A

In [37]:
# 3) Mostrar primeras 10 filas
print("Primeras 10 filas (ordenadas por País y Ciudad):")
df_sorted.head(10)

Primeras 10 filas (ordenadas por País y Ciudad):

,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional
21,Mia,Schneider Fischer,28973553Z,Alemanya,Berlín,22,10,1976,A,951 €,NaN,1.0,Grup A
154,Laura,Schneider Fischer,37399141L,Alemanya,Berlín,2,2,1958,D,1.769 €,1.0,NaN,Grup B
224,Lea,Schneider Schneider,37368317L,Alemanya,Berlín,23,10,2005,D,2.013 €,NaN,1.0,Grup B
278,Mia,Fischer,21390098Z,Alemanya,Berlín,11,8,1950,D,1.557 €,1.0,NaN,Grup B
602,Jonas,Schneider,44060014R,Alemanya,Berlín,22,11,1985,H,2.754 €,1.0,NaN,Grup D
871,Lea,Fischer,14773153R,Alemanya,Berlín,9,9,1986,D,1.370 €,1.0,NaN,Grup A
281,Lea,Müller,23266650S,Alemanya,Hamburg,14,4,2003,D,1.314 €,NaN,1.0,Grup A
435,Anna,Müller,83274277X,Alemanya,Hamburg,1,1,1987,D,2.464 €,NaN,1.0,Grup C
444,Laura,Schmidt Müller,60161784X,Alemanya,Hamburg,15,6,1987,NC,2.035 €,1.0,NaN,Grup C
487,Lukas,Müller Fischer,60982309S,Alemanya,Hamburg,28,3,1971,H,2.042 €,NaN,1.0,Grup B

In [38]:
# 4) Comprobación de unicidad del DNI
print("Comprobación del DNI:")
print(f"Total DNIs: {df_sorted['DNI'].size}")
print(f"DNIs únicos: {df_sorted['DNI'].nunique(dropna=True)}")
    
if df_sorted["DNI"].is_unique:
        print("La columna DNI contiene valores únicos.")
else:
        print("⚠️ Hay DNIs duplicados. Puedes verlos con:")
        print("   df_sorted[df_sorted.duplicated('DNI', keep=False)]")

Comprobación del DNI:
Total DNIs: 1000
DNIs únicos: 1000
La columna DNI contiene valores únicos.

In [39]:
# 4.1) Comprobación de unicidad del DNI mas sencilla
df_sorted["DNI"].is_unique

True

In [ ]:
# Nivel 1 - Punto 2

# 1) Crear columna "Nom complet"
df_sorted["Nom complet"] = df_sorted["Nom"] + " " + df_sorted["Cognoms"]

# Verificamos
df_sorted

,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Nom complet
21,Mia,Schneider Fischer,28973553Z,Alemanya,Berlín,22,10,1976,A,951 €,NaN,1.0,Grup A,Mia Schneider Fischer
154,Laura,Schneider Fischer,37399141L,Alemanya,Berlín,2,2,1958,D,1.769 €,1.0,NaN,Grup B,Laura Schneider Fischer
224,Lea,Schneider Schneider,37368317L,Alemanya,Berlín,23,10,2005,D,2.013 €,NaN,1.0,Grup B,Lea Schneider Schneider
278,Mia,Fischer,21390098Z,Alemanya,Berlín,11,8,1950,D,1.557 €,1.0,NaN,Grup B,Mia Fischer
602,Jonas,Schneider,44060014R,Alemanya,Berlín,22,11,1985,H,2.754 €,1.0,NaN,Grup D,Jonas Schneider
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
547,Emily,Taylor Jones,89577876S,Regne Unit,Manchester,28,3,1958,D,2.033 €,NaN,1.0,Grup B,Emily Taylor Jones
728,George,Brown Jones,57441590Y,Regne Unit,Manchester,27,12,1979,H,1.130 €,1.0,NaN,Grup A,George Brown Jones
751,Olivia,Brown Brown,58204038A,Regne Unit,Manchester,28,8,1952,A,1.023 €,NaN,1.0,Grup A,Olivia Brown Brown
854,Isla,Jones Brown,28367234K,Regne Unit,Manchester,28,3,1999,D,1.197 €,NaN,1.0,Grup A,Isla Jones Brown
872,William,Smith,82046699J,Regne Unit,Manchester,19,5,1997,H,1.405 €,1.0,NaN,Grup A,William Smith

In [ ]:
# 1.1)Reordenar columnas colocando "Nom complet" como tercera columna

# Generamos una lista con las columnas del df
cols = list(df_sorted.columns)

# Sacamos la columna de donde esté
cols.remove("Nom complet")

# La insertamos en la posición 2 (índice 2 → tercera columna)
cols.insert(2, "Nom complet")

# Aplicamos el nuevo orden
df_sorted = df_sorted[cols]

# Verificamos
df_sorted.head()

,Nom,Cognoms,Nom complet,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional
21,Mia,Schneider Fischer,Mia Schneider Fischer,28973553Z,Alemanya,Berlín,22,10,1976,A,951 €,NaN,1.0,Grup A
154,Laura,Schneider Fischer,Laura Schneider Fischer,37399141L,Alemanya,Berlín,2,2,1958,D,1.769 €,1.0,NaN,Grup B
224,Lea,Schneider Schneider,Lea Schneider Schneider,37368317L,Alemanya,Berlín,23,10,2005,D,2.013 €,NaN,1.0,Grup B
278,Mia,Fischer,Mia Fischer,21390098Z,Alemanya,Berlín,11,8,1950,D,1.557 €,1.0,NaN,Grup B
602,Jonas,Schneider,Jonas Schneider,44060014R,Alemanya,Berlín,22,11,1985,H,2.754 €,1.0,NaN,Grup D

In [42]:
# 2) Crear columna "Nascut a Espanya"
df_sorted["Nascut a Espanya"] = df_sorted["País d'origen"].apply(lambda x: "Sí" if x == "Espanya" else "No")

# Verificar
display(df_sorted[df_sorted["País d'origen"] == "Espanya"])

display(df_sorted[df_sorted["País d'origen"] != "Espanya"])

C:\Users\ramir\AppData\Local\Temp\ipykernel_8552\1949682870.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_sorted["Nascut a Espanya"] = df_sorted["País d'origen"].apply(lambda x: "Sí" if x == "Espanya" else "No")

,Nom,Cognoms,Nom complet,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Nascut a Espanya
1,Clara,Sánchez Martínez,Clara Sánchez Martínez,27724652S,Espanya,Barcelona,18,3,1996,D,1.253 €,1.0,NaN,Grup A,Sí
4,Toni,Sánchez García,Toni Sánchez García,69630528M,Espanya,Barcelona,9,8,1999,H,1.043 €,NaN,1.0,Grup A,Sí
9,Toni,Martínez,Toni Martínez,14219925Z,Espanya,Barcelona,16,5,1964,H,891 €,NaN,1.0,Grup A,Sí
10,Oriol,Sánchez,Oriol Sánchez,40695825B,Espanya,Barcelona,27,7,1965,H,1.250 €,NaN,1.0,Grup A,Sí
13,Toni,Castells Romero,Toni Castells Romero,74222289K,Espanya,Barcelona,13,4,1961,H,1.438 €,NaN,1.0,Grup B,Sí
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
944,Laia,Sánchez,Laia Sánchez,42807414J,Espanya,València,17,7,1967,D,2.255 €,NaN,1.0,Grup C,Sí
949,Núria,Martínez Ferrer,Núria Martínez Ferrer,38147748A,Espanya,València,4,11,1976,D,1.028 €,NaN,1.0,Grup A,Sí
958,Oriol,Sánchez García,Oriol Sánchez García,48749091Z,Espanya,València,16,7,1965,H,1.273 €,NaN,1.0,Grup A,Sí
961,Clara,Romero García,Clara Romero García,29019539A,Espanya,València,8,2,1989,D,1.246 €,1.0,NaN,Grup A,Sí
991,Carla,Ferrer Martínez,Carla Ferrer Martínez,22942395H,Espanya,València,3,5,1992,D,1.714 €,NaN,1.0,Grup B,Sí

,Nom,Cognoms,Nom complet,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Nascut a Espanya
21,Mia,Schneider Fischer,Mia Schneider Fischer,28973553Z,Alemanya,Berlín,22,10,1976,A,951 €,NaN,1.0,Grup A,No
154,Laura,Schneider Fischer,Laura Schneider Fischer,37399141L,Alemanya,Berlín,2,2,1958,D,1.769 €,1.0,NaN,Grup B,No
224,Lea,Schneider Schneider,Lea Schneider Schneider,37368317L,Alemanya,Berlín,23,10,2005,D,2.013 €,NaN,1.0,Grup B,No
278,Mia,Fischer,Mia Fischer,21390098Z,Alemanya,Berlín,11,8,1950,D,1.557 €,1.0,NaN,Grup B,No
602,Jonas,Schneider,Jonas Schneider,44060014R,Alemanya,Berlín,22,11,1985,H,2.754 €,1.0,NaN,Grup D,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
547,Emily,Taylor Jones,Emily Taylor Jones,89577876S,Regne Unit,Manchester,28,3,1958,D,2.033 €,NaN,1.0,Grup B,No
728,George,Brown Jones,George Brown Jones,57441590Y,Regne Unit,Manchester,27,12,1979,H,1.130 €,1.0,NaN,Grup A,No
751,Olivia,Brown Brown,Olivia Brown Brown,58204038A,Regne Unit,Manchester,28,8,1952,A,1.023 €,NaN,1.0,Grup A,No
854,Isla,Jones Brown,Isla Jones Brown,28367234K,Regne Unit,Manchester,28,3,1999,D,1.197 €,NaN,1.0,Grup A,No
872,William,Smith,William Smith,82046699J,Regne Unit,Manchester,19,5,1997,H,1.405 €,1.0,NaN,Grup A,No

In [43]:
# 3) Definir DNI como index

df_sorted = df_sorted.set_index("DNI")

# Verificar
df_sorted

,Nom,Cognoms,Nom complet,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Nascut a Espanya
DNI,,,,,,,,,,,,,,
28973553Z,Mia,Schneider Fischer,Mia Schneider Fischer,Alemanya,Berlín,22,10,1976,A,951 €,NaN,1.0,Grup A,No
37399141L,Laura,Schneider Fischer,Laura Schneider Fischer,Alemanya,Berlín,2,2,1958,D,1.769 €,1.0,NaN,Grup B,No
37368317L,Lea,Schneider Schneider,Lea Schneider Schneider,Alemanya,Berlín,23,10,2005,D,2.013 €,NaN,1.0,Grup B,No
21390098Z,Mia,Fischer,Mia Fischer,Alemanya,Berlín,11,8,1950,D,1.557 €,1.0,NaN,Grup B,No
44060014R,Jonas,Schneider,Jonas Schneider,Alemanya,Berlín,22,11,1985,H,2.754 €,1.0,NaN,Grup D,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
89577876S,Emily,Taylor Jones,Emily Taylor Jones,Regne Unit,Manchester,28,3,1958,D,2.033 €,NaN,1.0,Grup B,No
57441590Y,George,Brown Jones,George Brown Jones,Regne Unit,Manchester,27,12,1979,H,1.130 €,1.0,NaN,Grup A,No
58204038A,Olivia,Brown Brown,Olivia Brown Brown,Regne Unit,Manchester,28,8,1952,A,1.023 €,NaN,1.0,Grup A,No
28367234K,Isla,Jones Brown,Isla Jones Brown,Regne Unit,Manchester,28,3,1999,D,1.197 €,NaN,1.0,Grup A,No
82046699J,William,Smith,William Smith,Regne Unit,Manchester,19,5,1997,H,1.405 €,1.0,NaN,Grup A,No

In [ ]:
# 4) Sustituye el nombre de las columnas Día de Nacimiento, Mes de Nacimiento y Año de Nacimiento por Día, Mes y Año. (Aqui pude haber cambiado
                                                                                                                   # a ingles para el ejercicio date)

df_sorted = df_sorted.rename(columns={
    "Dia de Naixement": "Dia",
    "Mes de Naixement": "Mes",
    "Any de Naixement": "Any"
})

# Verificar
df_sorted

,Nom,Cognoms,Nom complet,País d'origen,Ciutat,Dia,Mes,Any,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Nascut a Espanya
DNI,,,,,,,,,,,,,,
28973553Z,Mia,Schneider Fischer,Mia Schneider Fischer,Alemanya,Berlín,22,10,1976,A,951 €,NaN,1.0,Grup A,No
37399141L,Laura,Schneider Fischer,Laura Schneider Fischer,Alemanya,Berlín,2,2,1958,D,1.769 €,1.0,NaN,Grup B,No
37368317L,Lea,Schneider Schneider,Lea Schneider Schneider,Alemanya,Berlín,23,10,2005,D,2.013 €,NaN,1.0,Grup B,No
21390098Z,Mia,Fischer,Mia Fischer,Alemanya,Berlín,11,8,1950,D,1.557 €,1.0,NaN,Grup B,No
44060014R,Jonas,Schneider,Jonas Schneider,Alemanya,Berlín,22,11,1985,H,2.754 €,1.0,NaN,Grup D,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
89577876S,Emily,Taylor Jones,Emily Taylor Jones,Regne Unit,Manchester,28,3,1958,D,2.033 €,NaN,1.0,Grup B,No
57441590Y,George,Brown Jones,George Brown Jones,Regne Unit,Manchester,27,12,1979,H,1.130 €,1.0,NaN,Grup A,No
58204038A,Olivia,Brown Brown,Olivia Brown Brown,Regne Unit,Manchester,28,8,1952,A,1.023 €,NaN,1.0,Grup A,No
28367234K,Isla,Jones Brown,Isla Jones Brown,Regne Unit,Manchester,28,3,1999,D,1.197 €,NaN,1.0,Grup A,No
82046699J,William,Smith,William Smith,Regne Unit,Manchester,19,5,1997,H,1.405 €,1.0,NaN,Grup A,No

In [45]:
# 5) Sustituye a H por Hombre, D por Mujer, A por Otros y NC por un dato faltante (null/na).

# 5.1) Comprobamos cuantos campos existe de cada tipo de dato

print(df_sorted["Gènere"].value_counts(dropna=False))

Gènere
H     449
D     440
NC     60
A      51
Name: count, dtype: int64

In [46]:
# 5.2) Realizamos los cambios solicitados

df_sorted["Gènere"] = df_sorted["Gènere"].replace({
    "H": "Home",
    "D": "Dona",
    "A": "Altres",
    "NC": np.nan
})

# Verificar
df_sorted

,Nom,Cognoms,Nom complet,País d'origen,Ciutat,Dia,Mes,Any,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Nascut a Espanya
DNI,,,,,,,,,,,,,,
28973553Z,Mia,Schneider Fischer,Mia Schneider Fischer,Alemanya,Berlín,22,10,1976,Altres,951 €,NaN,1.0,Grup A,No
37399141L,Laura,Schneider Fischer,Laura Schneider Fischer,Alemanya,Berlín,2,2,1958,Dona,1.769 €,1.0,NaN,Grup B,No
37368317L,Lea,Schneider Schneider,Lea Schneider Schneider,Alemanya,Berlín,23,10,2005,Dona,2.013 €,NaN,1.0,Grup B,No
21390098Z,Mia,Fischer,Mia Fischer,Alemanya,Berlín,11,8,1950,Dona,1.557 €,1.0,NaN,Grup B,No
44060014R,Jonas,Schneider,Jonas Schneider,Alemanya,Berlín,22,11,1985,Home,2.754 €,1.0,NaN,Grup D,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
89577876S,Emily,Taylor Jones,Emily Taylor Jones,Regne Unit,Manchester,28,3,1958,Dona,2.033 €,NaN,1.0,Grup B,No
57441590Y,George,Brown Jones,George Brown Jones,Regne Unit,Manchester,27,12,1979,Home,1.130 €,1.0,NaN,Grup A,No
58204038A,Olivia,Brown Brown,Olivia Brown Brown,Regne Unit,Manchester,28,8,1952,Altres,1.023 €,NaN,1.0,Grup A,No
28367234K,Isla,Jones Brown,Isla Jones Brown,Regne Unit,Manchester,28,3,1999,Dona,1.197 €,NaN,1.0,Grup A,No
82046699J,William,Smith,William Smith,Regne Unit,Manchester,19,5,1997,Home,1.405 €,1.0,NaN,Grup A,No

In [47]:
# 5.3) Comprobamos cuantos campos existe de cada tipo de dato después de la transformación 

print(df_sorted["Gènere"].value_counts(dropna=False))

Gènere
Home      449
Dona      440
NaN        60
Altres     51
Name: count, dtype: int64

In [48]:
# Nivel 1 - Punto 3
# 3) Junta las columnas Hijos y No Hijos en una sola columna, utilizando el método .apply() 
#    y definiendo una función que resuelva el problema. 
#    La columna nueva debe llamarse "Hijos" y tomar los valores "Sí" o "No"

# 3.1) Comprobamos que la cantidad de NaN en 'Fills' sea coherente con la cantidad de datos validos en 'No Fills' y viceversa

print(df_sorted["Fills"].value_counts(dropna=False))
print(df_sorted["No Fills"].value_counts(dropna=False))

Fills
NaN    594
1.0    406
Name: count, dtype: int64
No Fills
1.0    594
NaN    406
Name: count, dtype: int64

In [49]:
# 3.2) Creamos una funcion para normalizar los datos en una sola columna

def té_fills(row):
    if row["Fills"] == 1.0:
        return "Sí"
    elif row["No Fills"] == 1.0:
        return "No"
    else:
        return np.nan

In [50]:
# 3.3) Aplicamos la función a la columna 'Fills' 

df_sorted["Fills"] = df_sorted.apply(té_fills, axis=1)

df_sorted

,Nom,Cognoms,Nom complet,País d'origen,Ciutat,Dia,Mes,Any,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Nascut a Espanya
DNI,,,,,,,,,,,,,,
28973553Z,Mia,Schneider Fischer,Mia Schneider Fischer,Alemanya,Berlín,22,10,1976,Altres,951 €,No,1.0,Grup A,No
37399141L,Laura,Schneider Fischer,Laura Schneider Fischer,Alemanya,Berlín,2,2,1958,Dona,1.769 €,Sí,NaN,Grup B,No
37368317L,Lea,Schneider Schneider,Lea Schneider Schneider,Alemanya,Berlín,23,10,2005,Dona,2.013 €,No,1.0,Grup B,No
21390098Z,Mia,Fischer,Mia Fischer,Alemanya,Berlín,11,8,1950,Dona,1.557 €,Sí,NaN,Grup B,No
44060014R,Jonas,Schneider,Jonas Schneider,Alemanya,Berlín,22,11,1985,Home,2.754 €,Sí,NaN,Grup D,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
89577876S,Emily,Taylor Jones,Emily Taylor Jones,Regne Unit,Manchester,28,3,1958,Dona,2.033 €,No,1.0,Grup B,No
57441590Y,George,Brown Jones,George Brown Jones,Regne Unit,Manchester,27,12,1979,Home,1.130 €,Sí,NaN,Grup A,No
58204038A,Olivia,Brown Brown,Olivia Brown Brown,Regne Unit,Manchester,28,8,1952,Altres,1.023 €,No,1.0,Grup A,No
28367234K,Isla,Jones Brown,Isla Jones Brown,Regne Unit,Manchester,28,3,1999,Dona,1.197 €,No,1.0,Grup A,No
82046699J,William,Smith,William Smith,Regne Unit,Manchester,19,5,1997,Home,1.405 €,Sí,NaN,Grup A,No

In [51]:
# Eliminamos la columna 'No Fills'

df_sorted = df_sorted.drop(columns=["No Fills"])

#Verificamos

df_sorted

,Nom,Cognoms,Nom complet,País d'origen,Ciutat,Dia,Mes,Any,Gènere,Salari mensual,Fills,Grup Professional,Nascut a Espanya
DNI,,,,,,,,,,,,,
28973553Z,Mia,Schneider Fischer,Mia Schneider Fischer,Alemanya,Berlín,22,10,1976,Altres,951 €,No,Grup A,No
37399141L,Laura,Schneider Fischer,Laura Schneider Fischer,Alemanya,Berlín,2,2,1958,Dona,1.769 €,Sí,Grup B,No
37368317L,Lea,Schneider Schneider,Lea Schneider Schneider,Alemanya,Berlín,23,10,2005,Dona,2.013 €,No,Grup B,No
21390098Z,Mia,Fischer,Mia Fischer,Alemanya,Berlín,11,8,1950,Dona,1.557 €,Sí,Grup B,No
44060014R,Jonas,Schneider,Jonas Schneider,Alemanya,Berlín,22,11,1985,Home,2.754 €,Sí,Grup D,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...
89577876S,Emily,Taylor Jones,Emily Taylor Jones,Regne Unit,Manchester,28,3,1958,Dona,2.033 €,No,Grup B,No
57441590Y,George,Brown Jones,George Brown Jones,Regne Unit,Manchester,27,12,1979,Home,1.130 €,Sí,Grup A,No
58204038A,Olivia,Brown Brown,Olivia Brown Brown,Regne Unit,Manchester,28,8,1952,Altres,1.023 €,No,Grup A,No
28367234K,Isla,Jones Brown,Isla Jones Brown,Regne Unit,Manchester,28,3,1999,Dona,1.197 €,No,Grup A,No
82046699J,William,Smith,William Smith,Regne Unit,Manchester,19,5,1997,Home,1.405 €,Sí,Grup A,No

In [52]:
# Nivel 1 - Punto 4
# 4) Crea una tabla resumen que permita ver el sueldo medio, mediano, mínimo y máximo por Género.

# 4.1) Verificar que tipo de dato tiene la columna 'Salari mensual'

df_sorted["Salari mensual"].dtype

dtype('O')

In [53]:
# 4.2) Cambiar el nombre de la columna 'Salari mensual' por 'Salari mensual (€)'

df_sorted = df_sorted.rename(columns={
    "Salari mensual": "Salari mensual (€)"
})

df_sorted.head(0)

Empty DataFrame
Columns: [Nom, Cognoms, Nom complet, País d'origen, Ciutat, Dia, Mes, Any, Gènere, Salari mensual (€), Fills, Grup Professional, Nascut a Espanya]
Index: []

In [54]:
# 4.3) Eliminamos el signo (€) y el (.) de la columna 'Salari mensual (€)

df_sorted["Salari mensual (€)"] = (
    df_sorted["Salari mensual (€)"]
    .str.replace("€", "")
    .str.replace(".", "")
    .str.strip()
)


df_sorted.head(5)

,Nom,Cognoms,Nom complet,País d'origen,Ciutat,Dia,Mes,Any,Gènere,Salari mensual (€),Fills,Grup Professional,Nascut a Espanya
DNI,,,,,,,,,,,,,
28973553Z,Mia,Schneider Fischer,Mia Schneider Fischer,Alemanya,Berlín,22,10,1976,Altres,951,No,Grup A,No
37399141L,Laura,Schneider Fischer,Laura Schneider Fischer,Alemanya,Berlín,2,2,1958,Dona,1769,Sí,Grup B,No
37368317L,Lea,Schneider Schneider,Lea Schneider Schneider,Alemanya,Berlín,23,10,2005,Dona,2013,No,Grup B,No
21390098Z,Mia,Fischer,Mia Fischer,Alemanya,Berlín,11,8,1950,Dona,1557,Sí,Grup B,No
44060014R,Jonas,Schneider,Jonas Schneider,Alemanya,Berlín,22,11,1985,Home,2754,Sí,Grup D,No

In [55]:
# 4.4) Convertir la columna a tipo numérico

df_sorted["Salari mensual (€)"] = pd.to_numeric(
    df_sorted["Salari mensual (€)"]
)


df_sorted["Salari mensual (€)"].dtype

dtype('int64')

In [56]:
# 4.5) Realizamos los calculos solicitados

taula_salaris = (
    df_sorted
    .groupby("Gènere")["Salari mensual (€)"]
    .agg(
        sou_mig="mean",
        sou_mediana="median",
        sou_minim="min",
        sou_maxim="max"
    )
).round(2)

taula_salaris

        sou_mig  sou_mediana  sou_minim  sou_maxim
Gènere
Altres  1626.59       1545.0        703       3175
Dona    1469.44       1361.5        665       3021
Home    1643.25       1531.0        737       3356

In [ ]:
# 4.6) Ordena la tabla en función del sueldo medio.

taula_salaris = taula_salaris.sort_values(by="sou_mig")         #Por qué no me sale los valores NaN

taula_salaris

        sou_mig  sou_mediana  sou_minim  sou_maxim
Gènere
Dona    1469.44       1361.5        665       3021
Altres  1626.59       1545.0        703       3175
Home    1643.25       1531.0        737       3356

In [58]:
# Nivel 1 - Punto 5
# 5.1) Crea una tabla resumen con el salario medio por género (filas) y país de origen (columnas). 
#      Añade las medias a los márgenes de la tabla.

taula_genere_pais = pd.pivot_table(
    df_sorted,
    values="Salari mensual (€)",
    index="Gènere",
    columns="País d'origen",
    aggfunc="mean",
    margins=True,
    margins_name="Media total"
)

taula_genere_pais = taula_genere_pais.round(2)

taula_genere_pais

País d'origen,Alemanya,Argentina,Colòmbia,Espanya,França,Itàlia,Marroc,Mèxic,Portugal,Regne Unit,Media total
Gènere,,,,,,,,,,,
Altres,951.00,1141.00,1030.00,1706.18,NaN,1423.00,1365.00,1372.00,1765.00,1921.00,1626.59
Dona,1804.31,1291.80,1497.75,1460.16,1566.47,1247.18,1405.21,1517.80,1488.55,1489.46,1469.44
Home,2067.43,1583.29,1554.67,1682.11,1389.25,1672.88,1531.00,1625.00,1497.00,1162.56,1643.25
Media total,1851.38,1463.39,1495.54,1581.21,1462.73,1425.95,1447.33,1558.42,1523.33,1423.56,1560.99

In [59]:

# 5.3) (EXTRA): Aplica formato condicional en la tabla para ver en un color más intenso los valores más elevados

taula_genere_pais.style.format("{:,.2f} €").background_gradient(cmap="Greens")

In [60]:
# Visualizacion de valores mas grandes por filas (se visualiza mejor los valores mas grandes de cada gènero comparados por país)
taula_genere_pais.style.format("{:,.2F} €").background_gradient(cmap="Greens", axis=1)

In [61]:
# Visualizacion de valores mas grandes por columnas (se visualiza mejor los valores mas grandes  de cada país entre géneros)
  #Nos podemos dar cuenta que es igual a la primera visualizacion, es decir, si no se especifica axis = (algo) el valor predeterminado es axis=0

taula_genere_pais.style.format("{:,.2F} €").background_gradient(cmap="Greens", axis=0)

In [62]:
# Nivel 1 - Punto 6
# 6) Crea una nueva columna que sea la fecha de nacimiento en formato Datetime a partir de las columnas día, mes y año. 

# 6.1) Cambiamos los nombres de columna porque Pandas espera que los nombres exactos sean 'year', 'month' y 'day' 
     # cuando pasamos un DataFrame para pd.to_datetime()

df_sorted.rename(
    columns={"Any":"year","Mes":"month","Dia":"day"},
    inplace=True
)


df_sorted.head()

,Nom,Cognoms,Nom complet,País d'origen,Ciutat,day,month,year,Gènere,Salari mensual (€),Fills,Grup Professional,Nascut a Espanya
DNI,,,,,,,,,,,,,
28973553Z,Mia,Schneider Fischer,Mia Schneider Fischer,Alemanya,Berlín,22,10,1976,Altres,951,No,Grup A,No
37399141L,Laura,Schneider Fischer,Laura Schneider Fischer,Alemanya,Berlín,2,2,1958,Dona,1769,Sí,Grup B,No
37368317L,Lea,Schneider Schneider,Lea Schneider Schneider,Alemanya,Berlín,23,10,2005,Dona,2013,No,Grup B,No
21390098Z,Mia,Fischer,Mia Fischer,Alemanya,Berlín,11,8,1950,Dona,1557,Sí,Grup B,No
44060014R,Jonas,Schneider,Jonas Schneider,Alemanya,Berlín,22,11,1985,Home,2754,Sí,Grup D,No

In [66]:
# 6.2) Creamos la columna fecha de nacimiento

df_sorted["Data_naixement"] = pd.to_datetime(
df_sorted[["year", "month", "day"]]
)

# Comprobamos

df_sorted[["day", "month", "year", "Data_naixement"]].head()

           day  month  year Data_naixement
DNI
28973553Z   22     10  1976     1976-10-22
37399141L    2      2  1958     1958-02-02
37368317L   23     10  2005     2005-10-23
21390098Z   11      8  1950     1950-08-11
44060014R   22     11  1985     1985-11-22

In [64]:
# 6.3) Utilizando esta columna crea una función que dada una fecha, te calcule la edad actual a día de hoy.
from datetime import date

def calcular_edad(data_naixement):

    hoy = date.today()
    edad = hoy.year - data_naixement.year
    
    if (hoy.month, hoy.day) < (data_naixement.month, data_naixement.day):
        edad -= 1
        
    return edad

In [65]:
# 6.4) Utiliza la función que acabas de crear para generar una columna nueva en DataFrame con la edad actual.

df_sorted["Edat actual"] = df_sorted["Data_naixement"].apply(calcular_edad)

df_sorted[["Nom complet", "Data_naixement", "Edat actual"]].head()

                       Nom complet Data_naixement  Edat actual
DNI
28973553Z    Mia Schneider Fischer     1976-10-22           49
37399141L  Laura Schneider Fischer     1958-02-02           67
37368317L  Lea Schneider Schneider     2005-10-23           20
21390098Z              Mia Fischer     1950-08-11           75
44060014R          Jonas Schneider     1985-11-22           40